import type { Metadata, Viewport } from "next";
import localFont from "next/font/local";
import "./globals.css";

export const viewport: Viewport = {
  themeColor: "black",
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "PDH School",
  description: "Generated by create next app",
  keywords: [
    "PDH School",
    "Cohort 2",
    "startup building program",
    "aspiring entrepreneurs",
    "entrepreneurship course",
    "business skills",
    "technology skills",
    "startup community",
    "limited seats",
    "registration open",
    "discount on course fee",
    "mentorship for entrepreneurs",
    "startup journey",
    "build your startup",
    "entrepreneurship network",
    "industry experts",
    "business and tech program",
  ].join(", "),
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#101820]`}
      >
        {children}
      </body>
    </html>
  );
}
